baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "nightfall"

[params]
user = "Zac"
hostname = "zachooper.com"

  [params.author]
    name = "Zac Hooper"
    avatar = "/avatar.png"
    avatarSize = "size-m"
    email = "zac.g.hooper@gmail.com"

	[params.work]
	name = "TRENDii"
	url = "https://www.trendii.com"


	[[params.social]]
	key = 0
	name = "github"
	url = "https://github.com/ZacHooper"
	icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
	target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
	aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO

	[[params.social]]
	key = 1
	name = "linkedin"
	url = "https://www.linkedin.com/in/zachooper"
	icon = "fa-brands fa-linkedin"
	target = "_blank"
	aria = "LinkedIn Profile"

	[[params.social]]
	key = 2
	name = "email"
	url = "mailto:zac.g.hooper@gmail.com"
	icon = "fa-solid fa-envelope"
	target = "_blank"
	aria = "Email Zac Hooper"

[params.styles]
color = "orange"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "/posts"

[markup]
  [markup.highlight]
    style = "rose-pine"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
